# GitHub Pages configuration
name: AI News Daily
title: AI News Daily | Latest AI News and Research
description: Daily updates on AI and Machine Learning news, research, and insights.

# Force index.html to be the default page
# This setting is crucial for GitHub Pages to serve index.html instead of README
theme: jekyll-theme-minimal
baseurl: ""
url: "https://steviesimsii.github.io/AiNewsDaily/"

# Explicitly tell GitHub to use index.html
index_page: index.html
source: ./
markdown: kramdown
highlighter: rouge

# Settings for direct serving
exclude: ["README.txt", "README.md", "README", ".git"]
include: ["index.html", ".nojekyll"]

# Disable GitHub Pages from generating a page from README.md
readme_index:
  enabled: false
  remove_originals: false
