# GitHub Pages configuration
name: AI News Daily
title: AI News Daily | Latest AI News and Research
description: Daily updates on AI and Machine Learning news, research, and insights.

# Explicitly tell GitHub Pages we want to use the index file
# and not display the README by default
include: ["index.html"]
