name: Daily AI News Update

on:
  schedule:
    # Run every day at 14:00 UTC (8:00 AM CST)
    - cron: '0 14 * * *'
  # Allow manual trigger of the workflow
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser beautifulsoup4 pathlib
      
      - name: Run AI News Collector
        run: |
          python ai_news_collector.py
      
      - name: Deploy to GitHub Pages
        run: |
          python deploy_to_github.py
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Commit and push changes
        run: |
          git add docs ai_news.csv article_history.txt
          git add ai_news_collector.log deploy_to_github.log
          git diff --staged --quiet || git commit -m "Daily update: $(date +'%Y-%m-%d')"
          git push
